# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I Am The Vast Idled Hitchhiker
email: keith.m.davis.iii@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for data visualization, machine learning, and wandering the digital frontier.
  <br>"I Am The Vast Idled Hitchhiker" is an anagram of Keith Michael Davis the Third
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: KeithMDavisIII
github_username:  iamthevastidledhitchhiker

# Build settings
markdown: kramdown

